
server:
  port: 9900
spring:
  devtools:
    restart:
      enabled: true
  datasource:
    url: jdbc:mysql://localhost:3306/auto_function
    username: root
    password: Ramu@1999
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    
    
    
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
